# Generated by Django 4.1.7 on 2024-09-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='products/qr_images/', verbose_name='QR Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Прибыль'),
        ),
    ]
