# Generated by Django 4.1.7 on 2024-09-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_qr_image_alter_product_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка на продукт (%)'),
        ),
    ]
