# Generated by Django 4.1.7 on 2024-09-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_barcode_image',
            field=models.ImageField(blank=True, upload_to='products/manufacturer_barcode_image/', verbose_name='Фото штрих кода производителя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Количество на складе (по весу в кг, или по штучно)'),
        ),
    ]
