# Generated by Django 4.1.7 on 2024-09-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer_barcode_image',
            field=models.ImageField(blank=True, unique=True, upload_to='products/manufacturer_barcode_image/', verbose_name='Фото штрих кода производителя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_qr_code_image',
            field=models.ImageField(blank=True, unique=True, upload_to='products/manufacturer_qr_code_image/', verbose_name='Фото QR кода производителя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='my_generated_bar_code_image',
            field=models.ImageField(blank=True, unique=True, upload_to='products/my_generated_bar_code_image/', verbose_name='Фото штрих кода сгенерированного нами'),
        ),
        migrations.AlterField(
            model_name='product',
            name='my_generated_qr_code_image',
            field=models.ImageField(blank=True, unique=True, upload_to='products/my_generated_qr_code_image/', verbose_name='Фото QR кода сгенерированного нами'),
        ),
    ]
