# Generated by Django 4.1.7 on 2024-09-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer_barcode_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Текст штрих кода производителя'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_qr_code_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Текст QR кода производителя'),
        ),
        migrations.AddField(
            model_name='product',
            name='my_generated_bar_code_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Текст штрих кода сгенерированного нами'),
        ),
        migrations.AddField(
            model_name='product',
            name='my_generated_qr_code_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Текст QR кода сгенерированного нами'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_barcode_image',
            field=models.ImageField(blank=True, upload_to='products/manufacturer_barcode_image/', verbose_name='Фото штрих кода производителя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_qr_code_image',
            field=models.ImageField(blank=True, upload_to='products/manufacturer_qr_code_image/', verbose_name='Фото QR кода производителя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='my_generated_bar_code_image',
            field=models.ImageField(blank=True, upload_to='products/my_generated_bar_code_image/', verbose_name='Фото штрих кода сгенерированного нами'),
        ),
        migrations.AlterField(
            model_name='product',
            name='my_generated_qr_code_image',
            field=models.ImageField(blank=True, upload_to='products/my_generated_qr_code_image/', verbose_name='Фото QR кода сгенерированного нами'),
        ),
    ]
