# Generated by Django 4.1.7 on 2024-09-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer_barcode_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer_barcode_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer_qr_code_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer_qr_code_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='my_generated_qr_code_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='my_generated_qr_code_text',
        ),
        migrations.AddField(
            model_name='product',
            name='bar_code_image',
            field=models.ImageField(blank=True, upload_to='products/qr_code_image/', verbose_name='Фото QR кода'),
        ),
        migrations.AddField(
            model_name='product',
            name='bar_code_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Текст QR кода'),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code_image',
            field=models.ImageField(blank=True, upload_to='products/barcode_image/', verbose_name='Фото штрих кода'),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Текст штрих кода это будет slug_id'),
        ),
    ]
