# Generated by Django 4.1.7 on 2024-10-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_product_manufacturer_barcode_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bar_code_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qr_code_image',
        ),
    ]
