# Generated by Django 4.1.7 on 2024-10-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_product_bar_code_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bar_code_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Текст штрих кода'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_code_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Текст QR кода'),
        ),
    ]
