# Generated by Django 4.1.7 on 2024-10-11 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0020_product_price_sale_with_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма квитанции')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения квитанции')),
                ('kassir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кассир')),
                ('product', models.ManyToManyField(to='shop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Квитанция',
                'verbose_name_plural': 'Квитанции',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['-created'], name='shop_receip_created_66d206_idx'),
        ),
    ]
