# Generated by Django 4.1.7 on 2024-10-11 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_receipt_receipt_shop_receip_created_66d206_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='product',
        ),
        migrations.CreateModel(
            name='ReceiptProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.receipt')),
            ],
            options={
                'verbose_name': 'Продукт в квитанции',
                'verbose_name_plural': 'Продукты в квитанции',
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='products',
            field=models.ManyToManyField(through='shop.ReceiptProduct', to='shop.product', verbose_name='Продукты'),
        ),
    ]
