# Generated by Django 4.1.7 on 2024-10-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_product_bar_code_image_product_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bar_code_image',
            field=models.ImageField(blank=True, upload_to='products/barcode_image/', verbose_name='Фото штрих кода'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_code_image',
            field=models.ImageField(blank=True, upload_to='products/qr_code_image/', verbose_name='Фото QR кода'),
        ),
    ]
