# Generated by Django 4.1.7 on 2024-10-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_product_bar_code_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='changed',
            field=models.BooleanField(default='False', verbose_name='Отменено'),
        ),
    ]
