# Generated by Django 4.1.7 on 2024-10-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_receipt_changed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qr_code_text',
            new_name='code_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bar_code_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bar_code_text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qr_code_image',
        ),
        migrations.AddField(
            model_name='product',
            name='code_image',
            field=models.ImageField(blank=True, upload_to='products/code_image/', verbose_name='Фото QR кода'),
        ),
    ]
