# Generated by Django 4.1.7 on 2024-10-29 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0026_rename_qr_code_text_product_code_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CHANGE_PRODUCT', 'Добавление-Изменение продукта'), ('CHANGE_RECEIPT', 'Отмена квитанции'), ('CHANGE_DISCOUNT', 'Изменение скидки по категориям')], max_length=50, verbose_name='Тип действия')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('description', models.TextField(blank=True, verbose_name='Описание действия')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.receipt', verbose_name='Квитанция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
