# Generated by Django 4.1.7 on 2024-10-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_actionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='price_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена покупки'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='price_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена продажи'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='price_sale_with_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена продажи со скидкой'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Прибыль'),
        ),
    ]
