# Generated by Django 4.1.7 on 2024-10-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_remove_receipt_price_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptproduct',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка на продукт (%)'),
        ),
    ]
