# Generated by Django 4.1.7 on 2024-10-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_receiptproduct_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptproduct',
            name='product_slug',
            field=models.CharField(blank=True, max_length=264, verbose_name='Продукт slug'),
        ),
    ]
