# Generated by Django 4.1.7 on 2024-11-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_product_price_sale_optom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cubic_meter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Кубический метр'),
        ),
    ]
