# Generated by Django 4.1.7 on 2024-11-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_product_cubic_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kurs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='kurs'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_purchase',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена покупки manat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_sale',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи manat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_sale_optom',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена Оптовой продажи manat'),
        ),
    ]
