# Generated by Django 4.1.7 on 2024-11-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_product_price_purchase_manat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Курс')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='kurs',
        ),
    ]
