# Generated by Django 4.1.7 on 2024-11-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_kurs_remove_product_kurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='action_type',
            field=models.CharField(choices=[('CHANGE_PRODUCT', 'Добавление-Изменение продукта'), ('CHANGE_RECEIPT', 'Отмена квитанции'), ('CHANGE_DISCOUNT', 'Изменение скидки по категориям'), ('SET_SELL_PRICE', 'Установить цену по категориям'), ('SET_KURS', 'Установить курс')], max_length=50, verbose_name='Тип действия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_sale_with_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, verbose_name='Цена продажи со скидкой'),
        ),
    ]
