# Generated by Django 4.1.7 on 2024-11-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_alter_actionhistory_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptproduct',
            name='price_purchase_manat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена покупки манат'),
        ),
        migrations.AddField(
            model_name='receiptproduct',
            name='price_sale_manat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена продажи манат'),
        ),
        migrations.AddField(
            model_name='receiptproduct',
            name='profit_manat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Прибыль манат'),
        ),
    ]
