# Generated by Django 4.1.7 on 2024-11-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_receiptproduct_price_purchase_manat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='total_manat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма квитанции'),
        ),
    ]
