# Generated by Django 4.1.7 on 2024-11-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_alter_receipt_total_manat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_sale_with_discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='profit',
        ),
    ]
