# Generated by Django 4.1.7 on 2024-11-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_remove_product_description_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
