# Generated by Django 4.1.7 on 2024-11-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_remove_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptproduct',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='receiptproduct',
            name='price_sale_with_discount',
        ),
    ]
