# Generated by Django 4.1.7 on 2024-11-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_remove_receiptproduct_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cubic_meter',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Кубический метр'),
        ),
    ]
